version: '3.8'

services:
  # MySQL 数据库服务
  db:
    image: mysql:8.0
    container_name: crms_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crms
      MYSQL_USER: crms
      MYSQL_PASSWORD: cloResMgtsys
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crms_network
    restart: unless-stopped

  # Go 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crms_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - crms_network
    restart: unless-stopped

  # Nginx 前端服务
  frontend:
    image: nginx:alpine
    container_name: crms_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - crms_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  crms_network:
    driver: bridge