version: '3.8'

services:
  # MySQL 数据库服务
  db:
    image: mysql:8.0
    container_name: crms_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crms
      MYSQL_USER: crms
      MYSQL_PASSWORD: cloResMgtsys
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crms_network
    restart: unless-stopped

  # Redis 缓存服务
  redis:
    image: redis:alpine  # 使用轻量级 Alpine 版本
    container_name: crms_redis
    ports:
      - "6379:6379"      # 默认 Redis 端口
    volumes:
      - redis_data:/data  # 持久化 Redis 数据
    networks:
      - crms_network
    restart: unless-stopped

  # Go 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crms_backend
    depends_on:
      - db
      - redis           # 依赖 Redis 服务
    ports:
      - "8080:8080"
    networks:
      - crms_network
    restart: unless-stopped
    environment:
      REDIS_HOST: redis  # 通过服务名连接 Redis
      REDIS_PORT: 6379

  # Nginx 前端服务
  frontend:
    image: nginx:alpine
    container_name: crms_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - crms_network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:          # 新增 Redis 数据卷

networks:
  crms_network:
    driver: bridge